### ISSUE TITLE
"smb compression = yes" is not accepted in smb.conf on linux, tested via testparm

### ISSUE THREAD

**Issue by posta246** [VolkanSah/optimize-Samba-settings#3]
Hi,
on my Debian 12, the smb.conf file check says:
Unknown parameter encountered: "smb compression"
Ignoring unknown parameter "smb compression"
What is the right one? Is just wrong?
Bye!

**Comment by VolkanSah** [comment]
pleas use brain.bin! and read how to request help! bye!
