### ISSUE TITLE
"smb compression" does not seem to exist?

### ISSUE THREAD

**Issue by HorayNarea** [VolkanSah/optimize-Samba-settings#4]
I have build Samba 4.21.1 on Archlinux, I checked all flags that `./configure --help` lists, I read through the whole [smb.conf manpage](https://www.samba.org/samba/docs/current/man-html/smb.conf.5.html) and I've searched in the [Samba Gitlab](https://gitlab.com/samba-team/samba) … nowhere is `smb compression` mentioned and when I try to add that to my `smb.conf` and run `testparm -v` it says:

```
Unknown parameter encountered: "smb compression"
```

Could you be so kind and link to any place that documents the existence of this flag?

**Comment by VolkanSah** [comment]
### Thanks for wasting my time again.
**This issue has already been addressed, and the solution is clearly documented!**

It’s disappointing that you didn’t take the time to properly read the README or the linked documentation. As explicitly stated:
Use Modern Compression

Modern compression algorithms can significantly reduce the amount of data transmitted over the network. You can enable SMB compression in Samba:

`smb compression = yes`

    Enables SMB compression, which can significantly reduce the amount of data transmitted over the network.
    **Supported on Windows 10 and Windows Server 2019 or later.**

Please read this for details: SMB Compression Documentation.
Enable Multi-Channel Support

SMB3 introduced multi-channel support, allowing the use of multiple network connections for a single SMB session, increasing throughput and redundancy:

`server multi channel support = yes`

    Enables SMB3 multi-channel support, increasing throughput and redundancy.
    **Supported on Windows Server 2012 R2 and later.**

This information is already in the README. Ignoring these details and opening redundant issues is a waste of everyone’s time—including mine.

I strongly advise reading the Overview on how to request help, which provides guidance and emphasizes using the provided resources and your brain.

Your first mistake was failing to read; your last mistake is ignoring the answers in front of you. Moving forward, I’ll block you from this codebase if this happens again.

### Do better next time.
